### ISSUE TITLE
Leaflet viewer sometimes opens tiny

### ISSUE THREAD

**Issue by uschor** [ajwecker/TS1218#12]
Seems to reproduce when opening in private mode in Firefox

**Comment by ajwecker** [comment]
Still happens?

**Comment by uschor** [comment]
Sure. Wasn't fixed, afaik.

**Comment by drore** [comment]
Duplicate

**Comment by MosheLavee** [comment]
Still happened 10/2/2019 15:20
![image](https://user-images.githubusercontent.com/6770031/52534230-b4c13680-2d47-11e9-8085-a76f079e91cf.png)
