### ISSUE TITLE
Few issues in the marked.jspf file

### ISSUE THREAD

**Issue by MosheLavee** [ajwecker/TS1218#17]
@drore @ajwecker 
When inserting the Hebrew translations to TS1218/WebContent/WEB-INF/views/parts/HE/transcribe/marked.jspf 
I noticed few issues: 
1) Some images are missing - see the google file. This should be fixed both in the English and Hebrew version. 
2) We use < > in the text. This might cause a confution to the editor. 
3) dots, colons and other markers in the end of the Hebrew text jump to the beginning of the text. I hope they will appear rightly on the web page.

**Comment by ajwecker** [comment]
use &gt; and &lt;

**Comment by drore** [comment]
The missing images are in the hebrew version (might be on the fr version as well)
