### ISSUE TITLE
[LOW] invisible skip/fixed buttons and the actual page

### ISSUE THREAD

**Issue by TsvikaKuflik** [ajwecker/TS1218#18]
![image](https://user-images.githubusercontent.com/47208723/52401496-766b1380-2aca-11e9-819c-790fc247c89e.png)

**Comment by ajwecker** [comment]
Dror is this closed?

**Comment by MosheLavee** [comment]
@TsvikaKuflik I had the problem too but now it is fine. can you check now ?
