### ISSUE TITLE
[MEDIUM] defected images of letters 

### ISSUE THREAD

**Issue by MosheLavee** [ajwecker/TS1218#21]
The images of some letters in the אבג tab are spread and not clear: י ס ו are especially in bad shape, but also other letters. 
It seems that the letters were cut by a snipping tool with different resolution. @veredrk @drore can you fix this between the two of you ?

**Comment by ajwecker** [comment]
Also alphabet shouldn't have horizontal scroll

**Comment by MosheLavee** [comment]
@drore and @veredrk will collaborate to solve letter issues
