### ISSUE TITLE
bad apostrophes in http://tikkoun-sofrim.haifa.ac.il/TS1218/LoginServlet?page=views/team.jsp

### ISSUE THREAD

**Issue by uschor** [ajwecker/TS1218#22]
Probably non-unicode encoding of file

**Comment by ajwecker** [comment]
Not clear which file i problem navigation.jspf or team.jsp?

**Comment by uschor** [comment]
team.jsp, at the bottom, I think. I can handle it.

**Comment by ajwecker** [comment]
use &#39;
