### ISSUE TITLE
[MEDIUM] Hovers need translation

### ISSUE THREAD

**Issue by ajwecker** [ajwecker/TS1218#25]

**Comment by ajwecker** [comment]
this is the text on the title attribute

**Comment by ajwecker** [comment]
This includes the short description of the Geneva manuscript

**Comment by MosheLavee** [comment]
We missed the hover over the line fillers in the trinligual interface. 
I inseted it now in the [trilingual interface table](https://docs.google.com/spreadsheets/d/1J4cXV81P1TFkb5k3O8OjL_lPRzU3Ib2qB92xSOG7xj8/edit#gid=0) - 
I also fixed the english 'left' to 'right' according to the new direction of the screen. 
@dstoekl please add french translation and fix the french translation in accordances (lines 36 - 42) in the table. 
@ajwecker @drore please upload the updated version of the table after Daniel is done with translations.

**Comment by MosheLavee** [comment]
Hebrew and French overs are also missing of the reduce / increase size of text buttons. I added in the google sheet @dstoekl same same - please add French translations in the google shee (lines 43 - 44) @ajwecker @drore please upload the file after Daniel report that all translations are done.

**Comment by MosheLavee** [comment]
updating: Avigail did the French so @ajwecker or @drore can now push the new table in.

**Comment by dstoekl** [comment]
The French titles are all bound to the right instead of to the left (in paragraph layout).
Should we add <br> after "Besoin d'aide?:"
