### ISSUE TITLE
[HIGH] Scrolling logos and page image

### ISSUE THREAD

**Issue by TsvikaKuflik** [ajwecker/TS1218#27]
I used Opera browser and logged in to the hebrew version. 
The page image appeared as a small icon (already seen that in the past).
The logos are taking a large chunk of the screen and they are fixe and as a result, I could not see the done/skip buttons. Without knowing that they should be there, I would not have scrolled ...
Why are the logos fixed in that way?
![image](https://user-images.githubusercontent.com/47208723/52460110-72de9780-2b71-11e9-9506-2e5b70c8f636.png)

**Comment by ajwecker** [comment]
lower priority
