### ISSUE TITLE
add HTR page

### ISSUE THREAD

**Issue by dstoekl** [ajwecker/TS1218#30]
Please add English page on HTR  from gdoc

**Comment by ajwecker** [comment]
the htr should be multilingual.  it includes an htr.jspf which is separate
for each language

**Comment by dstoekl** [comment]
but in order to create translations all these multilingual pages need to be in the EN/FR/HE subdirectories


________________________________
De : ajwecker <notifications@github.com>
Envoyé : vendredi 8 février 2019 10:22
À : ajwecker/TS1218
Cc : Daniel Stoekl; Author
Objet : Re: [ajwecker/TS1218] add HTR page (#30)

the htr should be multilingual. it includes an htr.jspf which is separate
for each language

**Comment by ajwecker** [comment]
Agree.
Not sure who did this before and what was the process

**Comment by dstoekl** [comment]
I see the HTR page in the directory but it is not yet linked to the website interface.

**Comment by ajwecker** [comment]
fixed
