### ISSUE TITLE
Typo in the French page (?) and some other issues with content

### ISSUE THREAD

**Issue by TsvikaKuflik** [ajwecker/TS1218#36]
In the Frernch page "who we are"

Beam
(Alphabetical order)

There is no Hebrew content in "who we are" and the links lead to the English content for the about and Tanhuma

**Comment by dstoekl** [comment]
remaining French will be dealt with by Lily tomorrow. I have just added the French to this page on github. Needs to be uploaded however.

**Comment by dstoekl** [comment]
@avigailohali 
Please add Hebrew to https://github.com/ajwecker/TS1218/blob/master/TS1218/WebContent/WEB-INF/views/parts/HE/transcribe/marked.jspf

**Comment by avigailohali** [comment]
I corrected 2 errors.
Should the "special signs" part also be in this file?

**Comment by avigailohali** [comment]
Sorry, just saw that no.

**Comment by avigailohali** [comment]
Otherwise, I do not understand where is the missing hebrew.

**Comment by dstoekl** [comment]
If you look at at the files it has been converted into gibbrish. I do not know why. Only happened in this file.

**Comment by MosheLavee** [comment]
The file looks fine for me - do you see jibrish in the website or in the html? @dstoekl

**Comment by avigailohali** [comment]
Looks fine to me too...

**Comment by avigailohali** [comment]
Same thing for the Hebrew "about" page. On GitHub is looks fine, and on website it's in English.

**Comment by dstoekl** [comment]
@avigailohali 
Tous les exemples en hébreu sont toujours en jibbrish pour le marquage éditorial. Est-ce que tu pourrais le corriger stp?

**Comment by avigailohali** [comment]
Page corrected.

**Comment by dstoekl** [comment]
good morning. this page?
https://github.com/ajwecker/TS1218/blob/master/TS1218/WebContent/WEB-INF/views/parts/FR/transcribe/marked.jspf

**Comment by avigailohali** [comment]
Yes.

**Comment by dstoekl** [comment]
github does not show any change to it. last change was 17h ago by Alan.

**Comment by avigailohali** [comment]
I just saw that. I really don't understand. Found the page in french and
correcting it.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by avigailohali** [comment]
Seems fine now.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 11 févr. 2019 à 09:32, Avigail Ohali <avigail.ohali@gmail.com> a
écrit :

**Comment by dstoekl** [comment]
super. merci beaucoup.
