### ISSUE TITLE
there are no button texts for the translations of increase, decrease and font size

### ISSUE THREAD

**Issue by dstoekl** [ajwecker/TS1218#40]
in https://github.com/ajwecker/TS1218/tree/master/TS1218/src
in no language, not even in English as far as I can see
![image](https://user-images.githubusercontent.com/39535215/52526678-93ffcf00-2cbc-11e9-8bf8-8fa5def72fc9.png)

**Comment by ajwecker** [comment]
This working as designed since the text is hebrew. Maybe remove px
I would prefer symbols for all the button
half circle with arrow for reset (-) [+] {?} <~>

**Comment by dstoekl** [comment]
But we do have titles showing and they are in English even if the language is set to French

**Comment by ajwecker** [comment]
Titles indeed need msg texts
Advantage of symbols is that you dont need separate pictures for tutorials
