### ISSUE TITLE
could we choose different colors for the "done"  and "skip" buttons?

### ISSUE THREAD

**Issue by dstoekl** [ajwecker/TS1218#41]
They are in opposite places in LTR and RTL and at least I do need a color hint what to press. I would suggest green for "done" and yellow for "skip".
What does the system do when one hits return? Does it behave as if one has hit the "done" button or the "skip" button?

**Comment by ajwecker** [comment]
Colors done!
None of the 2 buttons have focus on start so return does nothing until buttons are tabbed to.
I don't think any of theses 2 button should have focus (transcription line has it and I think correct
