### ISSUE TITLE
[LOW] Make "help" label bold

### ISSUE THREAD

**Issue by drore** [ajwecker/TS1218#52]
Just wrap with <strong>

**Comment by dstoekl** [comment]
and red?

**Comment by ajwecker** [comment]
I think overkill

**Comment by dstoekl** [comment]
help button still not bold on my side

**Comment by dstoekl** [comment]
(and all the formatting I did on the French files is not updated either)

**Comment by MosheLavee** [comment]
Same is with the Hebrew, probably Alan will push it all in before the next deployment expected in about an hour from now.
