### ISSUE TITLE
visibility of skip/done on laptops

### ISSUE THREAD

**Issue by TsvikaKuflik** [ajwecker/TS1218#55]
Using a laptop, the Done/Skip buttons are invisible in the French version, partially visible in Emglish and better in Hebrew.
I suggest reducing the spece above the 👍 "Below is an automatic transcription. Please correct all errors in the text box.
This includes correcting misread or missing letters, and redundant or missing spaces." in all languages, to ensure visibility of Skip/Done

**Comment by dstoekl** [comment]
what is your screenresolution? I do see them on my laptop (1900 px)

**Comment by TsvikaKuflik** [comment]
Yes, 

This has to do with screen size and resolution.

I wonder if we would like to ensure any minimal standard (scrolling id OK, if you know that you need to do that, but it is better to avoid it).

Best,

 

 

Tsvika

 

Tsvi Kuflik, PhD.

 Professor of Information Systems

  Co-chair of the Digital Humanities BSc program,

  Information Systems department,

  The University of Haifa

  Email: tsvikak@is.haifa.ac.il <mailto:tsvikak@is.haifa.ac.il> 

  Home page:  <https://sites.hevra.haifa.ac.il/tsvikak> https://sites.hevra.haifa.ac.il/tsvikak

  Tel: +972 4 8288511

  Fax: +972 4 8288283
