### ISSUE TITLE
Manuscript page is still not not presented 

### ISSUE THREAD

**Issue by MosheLavee** [ajwecker/TS1218#64]
Using chorme the manuscript page is still not presented. @drore @ajwecker

**Comment by MosheLavee** [comment]
Now it is there! Yey.

**Comment by dstoekl** [comment]
very very small on this side of the mediterranean

**Comment by dstoekl** [comment]
now it works

**Comment by dstoekl** [comment]
sometimes, every third image or so, the page is still tiny tiny
