### ISSUE TITLE
[HIGH] Content for partners in all three languages is missing

### ISSUE THREAD

**Issue by ajwecker** [ajwecker/TS1218#65]

**Comment by ajwecker** [comment]
Who will update files (all 3 languages)
I can do build

**Comment by dstoekl** [comment]
text exists. Moshe is reviewing my Heb translation.

**Comment by dstoekl** [comment]
Moshe have you been able to advance on this?

**Comment by MosheLavee** [comment]
I already uploaded the Hebrew content without URLs. 
Please upload the French / English content with the URLs. 
You can see the paragraph I wrote about Haifa in the file

**Comment by dstoekl** [comment]
added the paragraphs on EPHE, PSL, Scripta and CHArt in this order. 
Is there already an English  / French version of the text of U Haifa?
Do you agree to put the French institutions before the Israeli ones, the latter having the promotion advantage of the URL?

**Comment by ajwecker** [comment]
I redid the English of eLijah lab
also some formatting.
I believe this applies to Frenc version as well

**Comment by veredrk** [comment]
I suggest putting one french first - the one best defines you, then eLijah
Lab, then other french and israeli institutions.
agreed?

‫בתאריך יום ג׳, 12 בפבר׳ 2019 ב-0:42 מאת ‪dstoekl‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by veredrk** [comment]
titles missing for the Hebrew (institutions names)

**Comment by MosheLavee** [comment]
@dstoekl as for the order of institutions - let elijah lab be first in Hebrew, French institutions first in French..
@veredrk can you add the titles in the html?

**Comment by dstoekl** [comment]
Just back from the train. II think it would be fairer to list the EPHE firsts also in Hebrew due to the URL with haifa in it anyhow.

**Comment by dstoekl** [comment]
Vered's suggestions seems a good idea to me.

**Comment by ajwecker** [comment]
in the french Elijah not even listed :-)

**Comment by ajwecker** [comment]
but seriously we need to freeze !

**Comment by veredrk** [comment]
I'll fix it now - He and En.
Daniel, which one  do you want first?

‫בתאריך יום ג׳, 12 בפבר׳ 2019 ב-12:32 מאת ‪ajwecker‬‏ <‪
notifications@github.com‬‏>:‬

> but seriously we need to freeze !
>

**Comment by dstoekl** [comment]
Lets do EPHE, eLijah, NLI and then PSL, Scripta, CHArt

**Comment by veredrk** [comment]
Daniel, can you send me the Fr for elijah lab?

‫בתאריך יום ג׳, 12 בפבר׳ 2019 ב-12:44 מאת ‪dstoekl‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by dstoekl** [comment]
It is already in the corresponding file. Please do not work on the FR file because I am working on it right now.

**Comment by veredrk** [comment]
so you'll add the URL for all institutions in the FR?

‫בתאריך יום ג׳, 12 בפבר׳ 2019 ב-13:29 מאת ‪dstoekl‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by ajwecker** [comment]
there is an extra /div & /p in the partners file

**Comment by veredrk** [comment]
I'm done with the content and URLs in the partners He and En files, please
fix the extra /divs.
we want the headers to be in a separate line, and with some space beween
each insitution.

‫בתאריך יום ג׳, 12 בפבר׳ 2019 ב-13:50 מאת ‪ajwecker‬‏ <‪
notifications@github.com‬‏>:‬

> there is an extra /div & /p in the partners file
>

**Comment by dstoekl** [comment]
which of the partners file contains extra /div andor /p, Alan?
French now with hyperlinks.
But we are still lacking the text for the NLI which is on the way.

**Comment by dstoekl** [comment]
@ajwecker 
could you please push the current versions of the partner files so that I could check the layout?
