### ISSUE TITLE
[high] please create automatic forward

### ISSUE THREAD

**Issue by dstoekl** [ajwecker/TS1218#67]
please create asap a page at https://tikkoun-sofrim.haifa.ac.il/ that automatically sends the user to the page on ts1218 so that we can send around only the short link, which is still very difficult and long but easier to explain.

**Comment by uschor** [comment]
Done.
Added the following lines in /etc/apache2/apache2.conf and restarted Apache HTTPd:
ProxyPass "/" "http://localhost:8080/TS1218/"
ProxyPassReverse "/" "http://localhost:8080/TS1218/"

**Comment by uschor** [comment]
You can access chapter pages like so: https://tikkoun-sofrim.haifa.ac.il/?ntn=154

**Comment by ajwecker** [comment]
how can I access a specific page line?

**Comment by MosheLavee** [comment]
http://tikkoun-sofrim.haifa.ac.il/TS1218/?m=Geneva_146&p=490&l=7

**Comment by ajwecker** [comment]
Uri done

**Comment by uschor** [comment]
As usual it's just a proxy definition. e.g.:
https://tikkoun-sofrim.haifa.ac.il/TS1218/TranscribeServlet

**Comment by dstoekl** [comment]
great. it works without https:// but it does not (from Paris) with the prefix https://

**Comment by dstoekl** [comment]
@urischor 
if I enter tikkoun-sofrim.haifa.ac.il in firefox, https:// is automatically prefixed and all I see is an empty page.
Can this be corrected somehow? Yesterday when writing the URL to my students it was a mess.

![image](https://user-images.githubusercontent.com/39535215/52628524-291ae780-2eb8-11e9-981a-87d9a85c3465.png)

**Comment by uschor** [comment]
I think it's cached (probably on a proxy somewhere in between).
Can you try again in private window? It works for me on FF.

**Comment by dstoekl** [comment]
yes it works on private window. so I just have to empty the cache?

**Comment by urischor** [comment]
I guess so. It will go by itself eventually.
