### ISSUE TITLE
No abs.jspf for English it is just a copy of Hebrew Version

### ISSUE THREAD

**Issue by ajwecker** [ajwecker/TS1218#73]
EN/abc.jspf

**Comment by dstoekl** [comment]
please roll it back. I have no idea how it happened but I must have made a wrong action.

**Comment by ajwecker** [comment]
I don't know from when.
It is prior to when I started tagging versions

**Comment by dstoekl** [comment]
ok. so at least it wasnt me. let me check how far we have to go back.

**Comment by dstoekl** [comment]
very long very long. dunno what happend. will try to recreate on the model of the French

**Comment by dstoekl** [comment]
Hey you just switched the French version to the Hebrew. Please go back

**Comment by ajwecker** [comment]
No it is okay there are two lines of Hebrew at the beginning
