### ISSUE TITLE
Firefox problem

### ISSUE THREAD

**Issue by TsvikaKuflik** [ajwecker/TS1218#92]
When using Firefox, after login, th epage image appears partially and without the transcribed line highlighted
![image](https://user-images.githubusercontent.com/47208723/53143727-f81a7100-35a1-11e9-8048-ea9991fba192.png)
after dragging the page it still does not appear
![image](https://user-images.githubusercontent.com/47208723/53143787-3dd73980-35a2-11e9-857d-a5df807e6adb.png)

**Comment by dstoekl** [comment]
see issue 58
